homework-6/problem-1/config/routes.rb
Rails.application.routes.draw do
  root 'cameras#index'
  resources(:cameras)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

homework-6/problem-1/app/models/camera.rb
class Camera < ApplicationRecord
  has_many :purchases
  has_many :users, through: cameras
end

homework-6/problem-1/app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :camera
  belongs_to :user
end

homework-6/problem-1/app/models/user.rb
class User < ApplicationRecord
  has_many :purchases
  has_many :cameras, through: :purchases
end

homework-6/problem-1/app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  def index
    @cameras = Camera.all
  end

  def show
    find_camera
  end

  def new
    @camera = Camera.new
  end

  def create
    @camera = Camera.create(camera_params)
  end

  def edit
    find_camera
  end

  def update
    find_camera
    @camera.update(camera_params)
    redirect_to_camera(cameras_path)
  end

  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy
    redirect_to(cameras_path)
  end


  private

  def find_camera
  @camera = Camera.find(params[:id])
  end

  def camera_params
  params[:camera].permit(:product_name,:price)
  end

  def redirect_to_camera(notice)
    redirect_to(@camera, notice: notice)
  end

end

homework-6/problem-1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

homework-6/problem-1/app/helpers/camera_helper.rb
module CameraHelper
  def edit_camera_link(camera)
  link_to('Edit', edit_camera_path(camera))
end

def delete_camera_link(camera)
  link_to('Delete', camera, method: :delete, data: {confirm: 'Are you sure?'})
end
end

homework-6/problem-1/app/helpers/home_helper.rb
module HomeHelper
end

homework-6/problem-1/app/views/home/index.html.erb
<h1>Hi this is your home controller index page!</h1>

homework-6/problem-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Problem2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <body>
    <nav>
      <p><%= link_to('All Cameras', root_path) %></p>
      <p><%= link_to('New Cameras', new_camera_path) %></p>
    </nav>

    <p><%= flash.notice %></p>

    <%= yield %>

    </body>
</html>