fake-twitter/config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
    root('tweets#index')
    resources(:tweets)
    resources(:users, only: [:index, :show, :edit, :update])

end

fake-twitter/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:twitter]

end

fake-twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method(:admin?)
  def admin?
    current_user.admin?
  end

end

fake-twitter/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

fake-twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action(:find_tweet, only: [:show, :edit, :update, :destroy])

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    # @tweet = Tweet.create(tweet_params.merge(user: current_user))
    @tweet = current_user.tweets.create(tweet_params)
    redirect_to_tweet_if_valid('You successfully created a tweet')
  end

  def edit
  end

  def update
    @tweet.update(tweet_params)
    redirect_to_tweet_if_valid('You successfully created a tweet')
  end

  def destroy
    @tweet.destroy
    redirect_to(tweets_path)
  end

  private

  def find_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    p = params[:tweet]
    p.permit(:title,:body,:location, :photo, :s3_region)
    # p.permit(:user_id) if current_user.admin?
    # p
  end

  def redirect_to_tweet_if_valid(notice)
    redirect_to(@tweet, notice: notice) if @tweet.valid?
  end

  def redirect_to_tweet(notice)
    redirect_to(@tweet, notice: notice)
  end

end

fake-twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end



end

fake-twitter/app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

fake-twitter/app/helpers/tweets_helper.rb
module TweetsHelper
  def edit_tweet_link(tweet)
    link_to('Edit', edit_tweet_path(tweet))
  end

  def delete_tweet_link(tweet)
    link_to('Delete', tweet, method: :delete, data: {confirm: 'Are you sure?'})
  end

end

fake-twitter/app/helpers/users_helper.rb
module UsersHelper
end

fake-twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FakeTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <% if user_signed_in? %>
    <p><%= current_user.email %></p>
    <p><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %></p>
  <% else %>
    <p><%= link_to('Log in', new_user_session_path) %></p>
    <p><%= link_to('Sign up', new_user_registration_path) %></p>
  <% end %>

  <p><%= link_to('All Tweets', root_path) %></p>
  <p><%= link_to('New Tweets', new_tweet_path) %></p>
  <p><%= link_to('Users', users_path) %></p>
</nav>

<p class="alert"><%= flash.alert %></p>
<p class="notice"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

fake-twitter/app/views/tweets/_form.html.erb
<% if request.post? && @tweet.invalid? %>
    <p>Uh oh, <%= pluralize(@tweet.errors.count, 'error') %>!</p>
    <ul>
        <% @tweet.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for(@tweet) do |f| %>
    <% if admin? %>
        <p>
            <%= f.label(:user) %>
            <%= f.collection_select(:user_id, User.all, :id, :email) %>
        </p>
    <% end %>
    <% if new_tweet || admin? %>
        <p>
            <%= f.label(:title) %>
            <%= f.text_field(:title, autofocus: true, placeholder: 'Tweet title goes here') %>
        </p>
    <% end %>
    <p>
        <%= f.label(:body) %>
        <%= f.text_area(:body) %>
        <% @tweet.errors[:body].each do |error| %>
            <div><%= error %></div>
        <% end %>
    </p>
    <p>
        <%= f.label(:location) %>
        <%= f.text_field(:location, placeholder: 'Where you tweeted from') %>
    </p>
    <p>
        <%= f.label(:photo) %>
        <%= f.file_field(:photo) %>
    </p>
    <p><%= f.submit(title) %></p>
<% end %>

fake-twitter/app/views/tweets/_tweet.html.erb
<div>
  <h2><%= link_to(tweet.title, tweet) %></h2>
  <p>By: <%= tweet.user.email %></p>
  <p><%= tweet.body %></p>
  <p>At: <%= tweet.location %></p>
  <p><%= image_tag(tweet.photo.url(:full)) %></p>
  <% if user_signed_in? %>
    <p> <%= edit_tweet_link(tweet) %></p>
    <p><%= delete_tweet_link(tweet) %></p>
  <% end %>
</div>

fake-twitter/app/views/tweets/create.html.erb
<h1>New Tweet</h1>

<p>
  <%= render('form', title: nil, new_tweet: true) %>
</p>

fake-twitter/app/views/tweets/destroy.html.erb
<h1>You have successfully deleted your tweet '<%= @tweet.title %>'</h1>

fake-twitter/app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render('form', title: 'EDIT', new_tweet: false) %>

fake-twitter/app/views/tweets/index.html.erb
<h1>All Tweets</h1>
<div>
    <%= render(@tweets) %>
  
</div>

fake-twitter/app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render('form', title: nil, new_tweet: true) %>

fake-twitter/app/views/tweets/show.html.erb
<h1>Show Tweet</h1>

<%= render(@tweet) %>

fake-twitter/app/views/tweets/update.html.erb
<h1>Updated Tweet</h1>

<p>
  <%= render('form', title: 'EDIT', new_tweet: false) %>
</p>

fake-twitter/app/views/users/_user.html.erb
<div>
<h1><%= link_to(user.email, user) %></h1>
</div>

fake-twitter/app/views/users/index.html.erb
<h1>Users</h1>

<%= render(@users) %>

fake-twitter/app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<%= render(@user.tweets) %>